stages:
  - initial
  - config
  - build
  - test
  - documentation
  - package
  - deploy
  # - cleanup

# cache:
#   # key: "$CI_PROJECT_NAME/$CI_BUILD_REF_NAME"
#   paths:
#     - build/
# variables:
#   CI_DEBUG_TRACE: "true"

init-macosx-py36:
  stage: initial
  script:
    # Crude way to remove and make sure directory is removed before creating a new one.
    # - cmake -E remove_directory build
    - cmake -E make_directory build_py36
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - macosx
  artifacts:
    paths:
      - build_py36/
  cache:
    paths:
      - build_py36/
      # TEMP workaround for default behaviour - to allow entire pipeline to keep moving should one particular job in a stage fail.
  allow_failure: true

init-macosx-py37:
  stage: initial
  script:
    # Crude way to remove and make sure directory is removed before creating a new one.
    # - cmake -E remove_directory build
    - cmake -E make_directory build_py37
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - macosx
  artifacts:
    paths:
      - build_py37/
  cache:
    paths:
      - build_py37/
      # TEMP workaround for default behaviour - to allow entire pipeline to keep moving should one particular job in a stage fail.
  allow_failure: true

init-windows-py36:
  stage: initial
  script:
    # Crude way to remove and make sure directory is removed before creating a new one.
    # - cmake -E remove_directory build
    - cmake -E make_directory build_py36
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - windows
  artifacts:
    paths:
      - build_py36/
  cache:
    paths:
      - build_py36/
  allow_failure: true

init-windows-py37:
  stage: initial
  script:
    # Crude way to remove and make sure directory is removed before creating a new one.
    # - cmake -E remove_directory build
    - cmake -E make_directory build_py37
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - windows
  artifacts:
    paths:
      - build_py37/
  cache:
    paths:
      - build_py37/
  allow_failure: true

init-linux:
  stage: initial
  script:
    - cmake -E make_directory build
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - linux
  artifacts:
    paths:
      - build/
  cache:
    paths:
      - build/
  allow_failure: true

init-linux-18:
  stage: initial
  script:
    - cmake -E make_directory build_18
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - linux-ubuntu-18
  artifacts:
    paths:
      - build_18/
  cache:
    paths:
      - build_18/
  allow_failure: true


# CMake Configuration:

linux-arch-config:
  stage: config
  dependencies:
    - init-linux
  script:
    - cmake -E chdir build/ cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON_BINDINGS=ON -DBUILD_JACK_SUPPORT=ON ..
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - linux
  artifacts:
    paths:
      - build/
  cache:
    paths:
      - build/
  allow_failure: true

linux-arch-config-18:
  stage: config
  dependencies:
    - init-linux-18
  script:
    - cmake -E chdir build_18/ cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON_BINDINGS=ON -DBUILD_JACK_SUPPORT=ON ..
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - linux-ubuntu-18
  artifacts:
    paths:
      - build_18/
  cache:
    paths:
      - build_18/
  allow_failure: true

windows-arch-config-py36:
  stage: config
  dependencies:
    - init-windows-py36
  script:
    - cmake -E chdir build_py36/ cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON_BINDINGS=ON -DPYTHON_INCLUDE_DIR=C:\ProgramData\Anaconda3\include -DPYTHON_LIBRARY=C:/ProgramData/Anaconda3/libs/python36.lib -DBOOST_ROOT=c:/local/dev/boost_1_67_0 ..
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - windows
  artifacts:
    paths:
      - build_py36/
  cache:
    paths:
      - build_py36/
  allow_failure: true

windows-arch-config-py37:
  stage: config
  dependencies:
    - init-windows-py37
  script:
    - cmake -E chdir build_py37/ cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON_BINDINGS=ON -DPYTHON_INCLUDE_DIR=C:\ProgramData\Anaconda3\envs\py37\include -DPYTHON_LIBRARY=C:\ProgramData\Anaconda3\envs\py37\libs\python37.lib -DBOOST_ROOT=c:/local/dev/boost_1_67_0 ..
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - windows
  artifacts:
    paths:
      - build_py37/
  cache:
    paths:
      - build_py37/
  allow_failure: true

macosx-arch-config-py36:
  stage: config
  dependencies:
    - init-macosx-py36
  script:
    - cmake -E chdir build_py36/ cmake -G "Xcode" -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON_BINDINGS=ON -DPYTHON_INCLUDE_DIR=/Users/williammorris/anaconda3/envs/py36/include/python3.6m -DPYTHON_LIBRARY=/Users/williammorris/anaconda3/envs/py36/lib/libpython3.6m.dylib -DBUILD_JACK_SUPPORT=ON ..
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - macosx
  artifacts:
    paths:
      - build_py36/
  cache:
    paths:
      - build_py36/
  allow_failure: true

macosx-arch-config-py37:
  stage: config
  dependencies:
    - init-macosx-py37
  script:
    - cmake -E chdir build_py37/ cmake -G "Xcode" -DCMAKE_BUILD_TYPE=Release -DBUILD_PYTHON_BINDINGS=ON -DPYTHON_INCLUDE_DIR=/Users/williammorris/anaconda3/envs/py37/include/python3.7m -DPYTHON_LIBRARY=/Users/williammorris/anaconda3/envs/py37/lib/libpython3.7m.dylib -DBUILD_JACK_SUPPORT=ON ..
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - macosx
  artifacts:
    paths:
      - build_py37/
  cache:
    paths:
      - build_py37/
  allow_failure: true

# Build:

linux-arch-build:
  stage: build
  dependencies:
    - linux-arch-config
  script:
    - cmake --build build/ --target --config Release
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - linux
  artifacts:
    paths:
      - build/
  cache:
    paths:
      - build/
  allow_failure: true

linux-arch-build-18:
  stage: build
  dependencies:
    - linux-arch-config-18
  script:
    - cmake --build build_18/ --target --config Release
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - linux-ubuntu-18
  artifacts:
    paths:
      - build_18/
  cache:
    paths:
      - build_18/
  allow_failure: true

windows-arch-build-py36:
  stage: build
  dependencies:
    - windows-arch-config-py36
  script:
    - cmake --build build_py36/ --target --config Release
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - windows
  artifacts:
    paths:
      - build_py36/
  cache:
    paths:
      - build_py36/
  allow_failure: true

windows-arch-build-py37:
  stage: build
  dependencies:
    - windows-arch-config-py37
  script:
    - cmake --build build_py37/ --target --config Release
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - windows
  artifacts:
    paths:
      - build_py37/
  cache:
    paths:
      - build_py37/
  allow_failure: true

macosx-arch-build-py36:
  stage: build
  dependencies:
    - macosx-arch-config-py36
  script:
    - cmake --build build_py36/ --target --config Release
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - macosx
  artifacts:
    paths:
      - build_py36/
  cache:
    paths:
      - build_py36/
  allow_failure: true

macosx-arch-build-py37:
  stage: build
  dependencies:
    - macosx-arch-config-py37
  script:
    - cmake --build build_py37/ --target --config Release
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - macosx
  artifacts:
    paths:
      - build_py37/
  cache:
    paths:
      - build_py37/
  allow_failure: true

# Test:

linux-arch-test:
  stage: test
  dependencies:
    - linux-arch-build
  script:
    - cmake --build build/ --target test --config Release
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - linux
  artifacts:
    paths:
    - Testing/*.log
    expire_in: 1 week
  # TEMP REMOVE THIS when tests are finished - TEMP
  allow_failure: true
  cache:
    paths:
      - build/

linux-arch-test-18:
  stage: test
  dependencies:
    - linux-arch-build-18
  script:
    - cmake --build build_18/ --target test --config Release
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - linux-ubuntu-18
  artifacts:
    paths:
    - Testing/*.log
    expire_in: 1 week
  # TEMP REMOVE THIS when tests are finished - TEMP
  allow_failure: true
  cache:
    paths:
      - build_18/

macosx-arch-test:
  stage: test
  dependencies:
    - macosx-arch-build-py36
  script:
    - cmake --build build_py36/ --target RUN_TESTS --config Release
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - macosx
  artifacts:
    paths:
    - Testing/*.log
    expire_in: 1 week
  # TEMP REMOVE THIS when tests are finished - TEMP
  allow_failure: true
  cache:
    paths:
      - build_py36/

# windows-arch-test:
#   stage: test
#   dependencies:
#     - windows-arch-build-py36
#   script:
#     - cmake --build build/ --target RUN_TESTS --config Release
#   only:
#     - master
#     - develop
#     - feature/experimental-ci
#   tags:
#     - windows
#   artifacts:
#     paths:
#     - Testing/*.log
#     expire_in: 1 week
#   # TEMP REMOVE THIS when tests are finished - TEMP
#   allow_failure: true
#   cache:
#     paths:
#       - build/

  # Documentation

linux-arch-doc:
  stage: documentation
  dependencies:
    - linux-arch-config
  script:
    - cmake --build build/ --target doc
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - linux
  artifacts:
    paths:
      - build/
  cache:
    paths:
      - build/
  allow_failure: true

windows-arch-doc:
  stage: documentation
  dependencies:
    - windows-arch-config-py36
  script:
    - cmake --build build_py37/ --target doc
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - windows
  artifacts:
    paths:
      - build_py36/
  cache:
    paths:
      - build_py36/
  allow_failure: true

macosx-arch-doc:
  stage: documentation
  dependencies:
    - macosx-arch-config-py36
  script:
    - cmake --build build_py36/ --target doc
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - macosx
  artifacts:
    paths:
      - build_py36/
  cache:
    paths:
      - build_py36/
  allow_failure: true

# Package - dependencies on build , test and package

linux-arch-package:
  stage: package
  dependencies:
    - linux-arch-build
  script:
    - cmake --build build/ --target package --config Release
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - linux
  artifacts:
    paths:
      - build/
  cache:
    paths:
      - build/
  allow_failure: true

linux-arch-package-18:
  stage: package
  dependencies:
    - linux-arch-build-18
  script:
    - cmake --build build_18/ --target package --config Release
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - linux-ubuntu-18
  artifacts:
    paths:
      - build_18/
  cache:
    paths:
      - build_18/
  allow_failure: true

windows-arch-package-py36:
  stage: package
  dependencies:
    - windows-arch-build-py36
  script:
    - cmake --build build_py36/ --target package --config Release
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - windows
  artifacts:
    paths:
      - build_py36/
  cache:
    paths:
      - build_py36/
  allow_failure: true

windows-arch-package-py37:
  stage: package
  dependencies:
    - windows-arch-build-py37
  script:
    - cmake --build build_py37/ --target package --config Release
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - windows
  artifacts:
    paths:
      - build_py37/
  cache:
    paths:
      - build_py37/
  allow_failure: true

macosx-arch-package-py36:
  stage: package
  dependencies:
    - macosx-arch-build-py36
  script:
    - cmake --build build_py36/ --target package --config Release
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - macosx
  artifacts:
    paths:
      - build_py36/
  cache:
    paths:
      - build_py36/
  allow_failure: true

macosx-arch-package-py37:
  stage: package
  dependencies:
    - macosx-arch-build-py37
  script:
    - cmake --build build_py37/ --target package --config Release
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - macosx
  artifacts:
    paths:
      - build_py37/
  cache:
    paths:
      - build_py37/
  allow_failure: true

# For internal, private deployment
linux-arch-deploy-int:
  stage: deploy
  dependencies:
    - linux-arch-package
  script:
    - rsync --recursive --delete build/doc/apidoc /vol/vssp/dataweb/data/s3a/public/VISR-API/
    - rsync --recursive --delete build/doc/userdoc /vol/vssp/dataweb/data/s3a/public/VISR-API/
  only:
    - master
    - develop
    # Testing branch for CI development
    - feature/experimental-ci
  tags:
    - linux
  artifacts:
    paths:
      - build/
  cache:
    paths:
      - build/
  allow_failure: true
